[tool.poetry]
name = "bidfax"
version = "0.1.0"
description = ""
authors = ["ilyaverb <verbiloilyaa@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.2"

[tool.poetry.group.dev.dependencies]
Django = "^4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
