# Generated by Django 4.2 on 2023-04-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_name',
            field=models.CharField(max_length=100, verbose_name='Имя аукциона'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='documents',
            field=models.CharField(max_length=100, verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='seller',
            field=models.CharField(max_length=100, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='information',
            name='estimate_coast',
            field=models.CharField(max_length=100, verbose_name='Оценочная стоимость'),
        ),
        migrations.AlterField(
            model_name='information',
            name='note',
            field=models.CharField(max_length=100, verbose_name='Примичяния'),
        ),
        migrations.AlterField(
            model_name='information',
            name='repair_price',
            field=models.CharField(max_length=100, verbose_name='Стоимость ремонта'),
        ),
    ]
